apiVersion: apps/v1
kind: Deployment
metadata:
  name: callerservice
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callerservice
  template:
    metadata:
      labels:
        app: callerservice
    spec:
      containers:
      - name: callerservice
        image: davidhu2023/callerservice:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: callerservice
spec:
  selector:
    app: callerservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

